main: net.kunmc.lab.branchialrespirationplugin.BranchialRespirationPlugin
name: BranchialRespirationPlugin
version: "0.1"
api: 1.16.5
api-version: 1.16
authors: [pon52]
description: えら呼吸プラグイン

commands:
  erakokyu:
      description: Get command help
      usage: /<command> help
      permission: op
      permission-message: 権限がありません